/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import info5100.university.example.Department.Department;
import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.StudentAccount;
import info5100.university.example.Persona.StudentDirectory;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Shreya Vivek Bhosale
 */
public class CreateStudentPage extends javax.swing.JFrame {

    Person person;
    StudentDirectory studentDirectory;
    Department department;

    /**
     * Creates new form CreateStudentPage
     */
    public CreateStudentPage() {
        initComponents();
        person = new Person();
        studentDirectory = new StudentDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textFieldStudID = new javax.swing.JTextField();
        textConfirmPassword = new javax.swing.JTextField();
        textStudName = new javax.swing.JTextField();
        textPhoneNum = new javax.swing.JTextField();
        createStudentButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textEmailID1 = new javax.swing.JTextField();
        textpassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CREATE STUDENT PAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(215, 226, 233));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STUDENT ID:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 110, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PHONE NUMBER:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, 25));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STUDENT NAME: ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMAIL ID:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        textFieldStudID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldStudIDActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldStudID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 320, 30));

        textConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(textConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 320, 30));
        jPanel3.add(textStudName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 320, 30));
        jPanel3.add(textPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 320, 30));

        createStudentButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        createStudentButton.setText("SAVE");
        createStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentButtonActionPerformed(evt);
            }
        });
        jPanel3.add(createStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 30));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONFIRM PASSWORD:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        textEmailID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailID1ActionPerformed(evt);
            }
        });
        jPanel3.add(textEmailID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 320, 30));

        textpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(textpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 320, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASSWORD:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AdminHomePage adminHomePage = new AdminHomePage();
        adminHomePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void textFieldStudIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldStudIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldStudIDActionPerformed

    private void textConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textConfirmPasswordActionPerformed

    private void createStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentButtonActionPerformed

        if (textFieldStudID.getText().isEmpty() || textStudName.getText().isEmpty() || textPhoneNum.getText().isEmpty() || textConfirmPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All values are mandatory", "Error", 0);
            return;
        }

        if (!textpassword.getText().equals(textConfirmPassword.getText())) {
            JOptionPane.showMessageDialog(null, "Password do not match", "Error", 0);
            return;
        }

        try {
            for (Map.Entry<String, StudentAccount> it : studentDirectory.getListOfStudents().entrySet()) {
                if (it.getKey().toString().equals(textFieldStudID.getText())) {
                    JOptionPane.showMessageDialog(null, "Existing student", "Error", 0);
                    return;
                }
            }

            String ph = textPhoneNum.getText();
            Long phoneNum = Long.parseLong(ph);
            studentDirectory.addStudentToDirectory(textFieldStudID.getText(), textStudName.getText(), textEmailID1.getText(), phoneNum, textpassword.getText());
            StudentAccount studentAccount = new StudentAccount();
            studentAccount.setId(textFieldStudID.getText());
            studentAccount.setName(textStudName.getText());
            studentAccount.setEmail(textEmailID1.getText());
            studentAccount.setPhoneNumber(phoneNum);
            studentAccount.setPassword(textpassword.getText());

            JOptionPane.showMessageDialog(this, "Student created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            textFieldStudID.setText("");
            textStudName.setText("");
            textEmailID1.setText("");
            textpassword.setText("");

        } catch (Exception e) {

        }

        /*if(airlineNameTextField.getText().isEmpty() || headQuartersTextField.getText().isEmpty()||countryTextField.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "All values are mandatory", "Error", 0);
          return;
        }
        try {
            for (Map.Entry<String, Airline> it : travelAgency.getListOfAirline().entrySet()) {
                if (it.getKey().toString().equals(airlineNameTextField.getText())) {
                    JOptionPane.showMessageDialog(null, "Exissting Airline", "Error", 0);
                    return;
                }
            }
            {                
                Airline airline = travelAgency.addAirline(airlineNameTextField.getText());
                airline.setNameOfAirline(airlineNameTextField.getText());
                airline.setMainHub(headQuartersTextField.getText());
                airline.setCountryOfOperation(countryTextField.getText());
                AirplaneFleet airplanefleet = new AirplaneFleet();
                airplanefleet.setAirline(airline);
                airline.setFleet(airplanefleet);
                FleetSchedule fleetSchedule = travelAgency.getSchedule().addFleetSchedule(airline);
                airline.setFleetschedule(fleetSchedule);
                fleetSchedule.setAirline(airline);
                JOptionPane.showMessageDialog(null, "Airline created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                airlineNameTextField.setText("");
                countryTextField.setText("");
                headQuartersTextField.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_createStudentButtonActionPerformed

    private void textEmailID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailID1ActionPerformed

    private void textpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createStudentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textConfirmPassword;
    private javax.swing.JTextField textEmailID1;
    private javax.swing.JTextField textFieldStudID;
    private javax.swing.JTextField textPhoneNum;
    private javax.swing.JTextField textStudName;
    private javax.swing.JTextField textpassword;
    // End of variables declaration//GEN-END:variables
}
